development:
  adapter: postgresql
  encoding: unicode
  database: jmetrics
  # database: review_trackers_production
  # database: review_trackers_production_backup_16_aug
  # database: review_trackers_production_backup_15_aug
  pool: 5
  username: postgres
  password: aarthiraj

# staging:
#   adapter: postgresql
#   encoding: unicode
#   database: review_trackers_development
#   pool: 5
#   username: postgres
#   password: aarthiraj


# production:
#   adapter: postgresql
#   encoding: unicode
#   database: review_trackers_development
#   pool: 5
#   username: postgres
#   password: aarthiraj